// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnXtTyvEH36tFWKh0xM9JUX9iyQ_Rshik',
    appId: '1:448830821403:web:2f76f1b291de554f8d54be',
    messagingSenderId: '448830821403',
    projectId: 'strawsmart-farming-af721',
    authDomain: 'strawsmart-farming-af721.firebaseapp.com',
    databaseURL: 'https://strawsmart-farming-af721-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'strawsmart-farming-af721.firebasestorage.app',
    measurementId: 'G-ZJP5RR5Q5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDieNF6tfpdZJgChOqKFqbM1vNy4j8X5wI',
    appId: '1:448830821403:android:695c4e71d00f15088d54be',
    messagingSenderId: '448830821403',
    projectId: 'strawsmart-farming-af721',
    databaseURL: 'https://strawsmart-farming-af721-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'strawsmart-farming-af721.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8iUvG9HhPD_Qxf0GXR_WdOxtA1pOUJEU',
    appId: '1:448830821403:ios:9f88957f766324818d54be',
    messagingSenderId: '448830821403',
    projectId: 'strawsmart-farming-af721',
    databaseURL: 'https://strawsmart-farming-af721-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'strawsmart-farming-af721.firebasestorage.app',
    iosBundleId: 'com.example.strawsmartFarming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8iUvG9HhPD_Qxf0GXR_WdOxtA1pOUJEU',
    appId: '1:448830821403:ios:9f88957f766324818d54be',
    messagingSenderId: '448830821403',
    projectId: 'strawsmart-farming-af721',
    databaseURL: 'https://strawsmart-farming-af721-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'strawsmart-farming-af721.firebasestorage.app',
    iosBundleId: 'com.example.strawsmartFarming',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnXtTyvEH36tFWKh0xM9JUX9iyQ_Rshik',
    appId: '1:448830821403:web:053bb59f1cfa8b018d54be',
    messagingSenderId: '448830821403',
    projectId: 'strawsmart-farming-af721',
    authDomain: 'strawsmart-farming-af721.firebaseapp.com',
    databaseURL: 'https://strawsmart-farming-af721-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'strawsmart-farming-af721.firebasestorage.app',
    measurementId: 'G-HRK94VM2ZD',
  );
}
